const sectionList = [
    {
        id:"1",
        name:"Syed",
        class:{id:"12c",className:"12"}
    },
    {
        id:"2",
        name:"Ahamed",
        class:{id:"12c",className:"12"}
    },
    {
        id:"3",
        name:"Shahul",
        class:{id:"12c",className:"12"}
    },
    {
        id:"4",
        name:"Hameed",
        class:{id:"12c",className:"12"}
    },
    {
        id:"5",
        name:"Abdul",
        class:{id:"12c",className:"12"}
    },
    {
        id:"6",
        name:"Kather",
        class:{id:"11c",className:"11"}
    },
    {
        id:"7",
        name:"Meeran",
        class:{id:"11c",className:"11"}
    },
    {
        id:"8",
        name:"Mohaideen",
        class:{id:"11c",className:"11"}
    },
    {
        id:"9",
        name:"Abdullah",
        class:{id:"11c",className:"11"}
    },
    {
        id:"10",
        name:"Kamil",
        class:{id:"11c",className:"11"}
    },
    {
        id:"11",
        name:"Yaseen",
        class:{id:"10c",className:"10"}
    },
    {
        id:"12",
        name:"Aziz",
        class:{id:"10c",className:"10"}
    },
    {
        id:"13",
        name:"Moosa",
        class:{id:"10c",className:"10"}
    },
    {
        id:"14",
        name:"Mohammed",
        class:{id:"10c",className:"10"}
    },
    {
        id:"15",
        name:"Latheef",
        class:{id:"10c",className:"10"}
    },
]
export function getSection(){
    return sectionList;
}